name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  view-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List all workflow runs for the pull request
      id: list-runs
      run: |
        echo "::set-output name=workflow-runs::$(jq -nc "$GITHUB" | jq '{repo: .repository.full_name, pr_number: .event.number, sha: .event.pull_request.head.sha}')"

    - name: Display workflow runs
      run: |
        echo "Workflow runs for PR ${{ github.event.pull_request.number }}:"
        echo "${{ steps.list-runs.outputs.workflow-runs }}"
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
