name: Auto Merge on Green Checks with Label

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types: [completed]
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check workflows status
        uses: actions/github-script@v7
        id: check_status
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const sha = context.payload.pull_request.head.sha;
  
            const { data: statuses } = await github.request('GET /repos/:owner/:repo/commits/:sha/check-runs', {
              owner,
              repo,
              sha
            });
            
            const actionStatuses = statuses.check_runs.map(checkRun => ({
              name: checkRun.name,
              conclusion: checkRun.conclusion
            }));

            console.log('actionStatuses', actionStatuses);
            
            const currentActionName = 'automerge';
            
            const isAllChecksArePassed = statuses.check_runs
              .filter(checkRun => checkRun.name !== currentActionName)
              .every(checkRun => checkRun.conclusion === 'success');

            console.log('The returned status of the tests is : ', isAllChecksArePassed);
  
            return isAllChecksArePassed;

      - name: Get result of prev step
        run: echo "${{steps.check_status.outputs.result}}"

      - name: Check if automerge label is == true
        run: echo "${{contains(github.event.pull_request.labels.*.name, 'automerge') == true }}"

      - name: Check if result like label is == true
        run: echo "${{contains(steps.check_status.outputs.result, true) == true }}"

      - name: Set Git Config
        run: |
          export GIT_COMMITTER_NAME='Automerge GitHub Action'
          export GIT_COMMITTER_EMAIL='actions@github.com'
          export GIT_AUTHOR_NAME='Automerge GitHub Action'
          export GIT_AUTHOR_EMAIL='actions@github.com'

      - name: Get pull request number
        run: echo "::set-output name=number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: Merge Pull Requests with automerge label
        run: |
          PR_NUMBER=$(echo "${{ steps.pr.outputs.number }}")
          git -c user.name='Automerge GitHub Action' -c user.email='actions@github.com' fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
          git merge --no-ff pr-$PR_NUMBER
