name: automerge
on:
  check_suite:
    branches:
      - ${{ github.event.pull_request.head.ref }}
    types: [completed]
jobs:
  waitForWorkflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for workflows
        uses: actions/github-script@v6
        id: set-result
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: statuses } = await github.request('GET /repos/:owner/:repo/commits/:sha/check-runs', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha
            });

            const actionStatuses = statuses.check_runs.map(checkRun => ({
              name: checkRun.name,
              conclusion: checkRun.conclusion
            }));

            const currentActionName = 'Wait for workflows';
            const check = statuses.check_runs
              .filter(checkRun => checkRun.name !== currentActionName)
              .every(checkRun => {
                console.log('checkRun', checkRun.name, checkRun.conclusion === 'success');
                return checkRun.conclusion === 'success'
              });

            console.log('current action: ', currentActionName);
            
            console.log('results', check);

            console.log('details', actionStatuses);

            console.log('all details', statuses);

            if ( !check ) {
              return false
            }

            console.log('continue');
            return true;
    
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

      - name: Writing
        if: ${{ steps.set-result.outputs.result == 'true' && 'm' == 'm' }}
        run: echo "${{needs.waitForWorkflows.outputs.status}}"

      - name: Install dependencies
        run: echo "Running npm test... " + needs.waitForWorkflows.outputs.status
