name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  waitForWorkflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const merge_method = 'rebase'; // Can be 'merge', 'squash' or 'rebase'
            
            // Fetch PR details
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });

            console.log('all details', pullRequest);

  afterWait:
    name: after-wait
    needs: [waitForWorkflows]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check needs results
        if: needs.waitForWorkflows.result != 'success'
        run: exit 1
