name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: Automerge GitHub Action
      GIT_COMMITTER_EMAIL: actions@github.com
      GIT_AUTHOR_NAME: Automerge GitHub Action
      GIT_AUTHOR_EMAIL: actions@github.com
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
