name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  waitForWorkflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: statuses } = await github.request('GET /repos/:owner/:repo/commits/:sha/check-runs', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha
            });

            const actionStatuses = statuses.check_runs.map(checkRun => ({
              name: checkRun.name,
              conclusion: checkRun.conclusion
            }));

            const currentActionName = context.job;
            const actionStatuses2 = statuses.check_runs
              .filter(checkRun => checkRun.name !== currentActionName)
              .every(checkRun => checkRun.conclusion === 'success');

            console.log('current action: ', currentActionName);
            
            console.log('results', actionStatuses2);

            console.log('details', actionStatuses);

            console.log('all details', statuses);

  afterWait:
    name: after-wait
    needs: [waitForWorkflows]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check needs results
        if: needs.waitForWorkflows.result != 'success'
        run: exit 1
