name: workflow-last

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  always_last:
    name: always_last
    runs-on: ubuntu-latest
    steps:
      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@latest  

      - name: Resume and run once, after all workflows are completed
        run: date
