name: Simulate npm test
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
          
      - name: Install dependencies
        run: echo "Running npm test..."
