name: Simulate npm test
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sleep for 1 minute
        run: sleep 60s
        shell: bash
        
    - name: Install dependencies
      run: echo "Running npm test..."
